### ISSUE TITLE
Cannot Select Folder For Import

### ISSUE THREAD

**Issue by aldman123** [Praxxian/lava-flow#16]
Hello!

I just started using your module, but I cannot select any folders. I browse to the folder I want, hit select folder, and then it still says "No file chosen".

![Screenshot (15)](https://user-images.githubusercontent.com/11451815/182043032-812da5b2-41f1-4189-bf85-d7da30488da7.png)
![Screenshot (14)](https://user-images.githubusercontent.com/11451815/182043035-09486085-6d0f-42ac-8465-94184d669a62.png)

Windows 11
Foundry VTT 9 Build 269
Lava Flow 1.1.0

**Comment by Praxxian** [comment]
Hi! Are you by any chance using the desktop app instead of a browser?

The version of Electron used in v9 has a bug with webkitdirectory, meaning the import function does not work in the desktop app. Easy workaround: access your instance through your web browser instead by going to http://localhost:30000/ while the desktop app is running.

**Comment by aldman123** [comment]
Yes I was using the desktop app. I didn't realize this was a known bug. Thank you!
