### ISSUE TITLE
Foundry VTT v12 Compatibility

### ISSUE THREAD

**Issue by Praxxian** [Praxxian/lava-flow#59]
I still need to confirm the module works with the latest stable release. From the release notes, I am optimistic that it should justwerk™️, but at a minimum I will need to update the compatibility doc and the module's entry with Foundry to show it is v12 compatible.

**Comment by Praxxian** [comment]
There is an issue when trying to add player permissions. Looks like a change in the constants.

Instead of `CONST.DOCUMENT_PERMISSION_LEVELS.OBSERVER` it should be `CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER`.

Have not fully ruled out other bugs, but this is the most visible. It will stop one from importing if they use the observe option.

**Comment by carolinex** [comment]
I have been testing locally and import doesn't work well on v12. The main issue for me is with creation of folders and subfolders. I wan to import the whole vault into one folder, but it keeps spreading its contents in the root, even if I type in a "top journal folder". The processing of the markdown itself seems to be working ok.

**Comment by wilkinsalex** [comment]
I have the same main issue as crlgn, the folders all import to the root of Foundry, even tested folders. The content (Markdown, links between journals etc.) all work properly as well as images. It is just the folder import. 

I don't think the extension can "see" the folders, because it doesn't overwrite them either even when the box is checked. The module thinks the folders do not exist and just duplicate it all. 

I had a test folder from Obsidian that has folders like this

Player Vault
- About
- Literature
- - Test
- Locations

There was one article in the Player Vault folder. Obsidian made all 5 of the above folders as root journal folders.

**Comment by deathtome1998** [comment]
hope to see this updated. I might be becoming a DM here at some point, and I was going to use foundry and obsidian so this plugin would be a lifesaver.

**Comment by wilkinsalex** [comment]
@deathtome1998 the pull request by Matt-Duffy turned into a separate fork for now. I set it up on V12 and it works perfectly. Obsidian is a game changer for DnD prep   you should check it out! You just need to grab the manifest URL from their page and toss it in your add module and it'll install.

**Comment by Praxxian** [comment]
The permission and folder issues are fixed in the latest release, 4.0.0. Thanks for your patience!
